In [1]:
from ozclim import tools
import xarray as xr 
import matplotlib.pyplot as plt
import seaborn as sns 
import numpy as np 
from scipy import stats 

import warnings
warnings.filterwarnings("ignore")

%matplotlib inline
%load_ext autoreload
%autoreload 2

In [2]:
ref = tools.get_ensemble_ds("ref", "MDA8_O3")*1e9 # ppbv
refSNOx = tools.get_ensemble_ds("refSNOx", "MDA8_O3")*1e9 # ppbv

refshort = tools.get_ensemble_ds("refshort", "MDA8_O3")*1e9 # ppbv
refSNOxshort = tools.get_ensemble_ds("refSNOxshort", "MDA8_O3")*1e9 # ppbv

polshort = tools.get_ensemble_ds("pol3.7short", "MDA8_O3")*1e9 # ppbv
polSNOxshort = tools.get_ensemble_ds("pol3.7SNOxshort", "MDA8_O3")*1e9 # ppbv

['/Users/emmie/Documents/OZCLIM_local/data/GCHP_CAM_c48_20240312/GCHP.w10_ref_c48.MDA8_O3.nc4']
['/Users/emmie/Documents/OZCLIM_local/data/GCHP_CAM_c48_20240312/GCHP.w13_ref_c48.MDA8_O3.nc4']
['/Users/emmie/Documents/OZCLIM_local/data/GCHP_CAM_c48_20240312/GCHP.w14_ref_c48.MDA8_O3.nc4']
['/Users/emmie/Documents/OZCLIM_local/data/GCHP_CAM_c48_20240312/GCHP.w26_ref_c48.MDA8_O3.nc4']
['/Users/emmie/Documents/OZCLIM_local/data/GCHP_CAM_c48_20240312/GCHP.w28_ref_c48.MDA8_O3.nc4']
['/Users/emmie/Documents/OZCLIM_local/data/GCHP_CAM_c48_20240312/GCHP.w10_refSNOx_c48.MDA8_O3.nc4']
['/Users/emmie/Documents/OZCLIM_local/data/GCHP_CAM_c48_20240312/GCHP.w13_refSNOx_c48.MDA8_O3.nc4']
['/Users/emmie/Documents/OZCLIM_local/data/GCHP_CAM_c48_20240312/GCHP.w14_refSNOx_c48.MDA8_O3.nc4']
['/Users/emmie/Documents/OZCLIM_local/data/GCHP_CAM_c48_20240312/GCHP.w26_refSNOx_c48.MDA8_O3.nc4']
['/Users/emmie/Documents/OZCLIM_local/data/GCHP_CAM_c48_20240312/GCHP.w28_refSNOx_c48.MDA8_O3.nc4']
['/Users/emmie/Docum

In [3]:
present_ratio = refSNOx/ref
future_ratio = refSNOxshort/refshort
futurepol_ratio = polSNOxshort/polshort

In [4]:
present_ratio_noland = tools.mask_ocean_c48(present_ratio)
future_ratio_noland = tools.mask_ocean_c48(future_ratio)
futurepol_ratio_noland = tools.mask_ocean_c48(futurepol_ratio)

In [32]:
# Eastern North America
region_num = 5

present_ratio_noland_region = tools.crop_regionmask_ar6_c48(present_ratio_noland, region_num)
future_ratio_noland_region = tools.crop_regionmask_ar6_c48(future_ratio_noland, region_num)  
futurepol_ratio_noland_region = tools.crop_regionmask_ar6_c48(futurepol_ratio_noland, region_num)

present = present_ratio_noland_region['SpeciesConc_O3'].isel(lev=0, region=0, drop=True)
future = future_ratio_noland_region['SpeciesConc_O3'].isel(lev=0, region=0, drop=True)
futurepol = futurepol_ratio_noland_region['SpeciesConc_O3'].isel(lev=0, region=0, drop=True)

prev_dO3_dNOx = present.shift(time=1)
transition = ((prev_dO3_dNOx < 1) & (present > 1))
transition_max = transition.sum(dim='time').max(dim=['nf', 'Ydim', 'Xdim'])
print(transition_max.values)

transition_min= transition.sum(dim='time').min(dim=['nf', 'Ydim', 'Xdim'])
print(transition_min.values)

transition_mean= transition.sum(dim='time').mean(dim=['nf', 'Ydim', 'Xdim'])
print(transition_mean.values)

[574 587 582 602 616]
[0 0 0 0 0]


In [36]:
# West-Central Europe
region_num = 17

present_ratio_noland_region = tools.crop_regionmask_ar6_c48(present_ratio_noland, region_num)
future_ratio_noland_region = tools.crop_regionmask_ar6_c48(future_ratio_noland, region_num)  
futurepol_ratio_noland_region = tools.crop_regionmask_ar6_c48(futurepol_ratio_noland, region_num)

present = present_ratio_noland_region['SpeciesConc_O3'].isel(lev=0, region=0, drop=True)
future = future_ratio_noland_region['SpeciesConc_O3'].isel(lev=0, region=0, drop=True)
futurepol = futurepol_ratio_noland_region['SpeciesConc_O3'].isel(lev=0, region=0, drop=True)

prev_dO3_dNOx = present.shift(time=1)
transition = ((prev_dO3_dNOx < 1) & (present > 1))
transition_max = transition.sum(dim='time').max(dim=['nf', 'Ydim', 'Xdim'])
print(transition_max.values)

transition_min= transition.sum(dim='time').min(dim=['nf', 'Ydim', 'Xdim'])
print(transition_min.values)

transition_mean= transition.sum(dim='time').mean(dim=['nf', 'Ydim', 'Xdim'])
print(transition_mean.values)

[653 615 669 694 639]
[0 0 0 0 0]
[2.51605903 2.47178819 2.48010706 2.46614583 2.55598958]


In [37]:
# West-Central Europe
region_num = 35

present_ratio_noland_region = tools.crop_regionmask_ar6_c48(present_ratio_noland, region_num)
future_ratio_noland_region = tools.crop_regionmask_ar6_c48(future_ratio_noland, region_num)  
futurepol_ratio_noland_region = tools.crop_regionmask_ar6_c48(futurepol_ratio_noland, region_num)

present = present_ratio_noland_region['SpeciesConc_O3'].isel(lev=0, region=0, drop=True)
future = future_ratio_noland_region['SpeciesConc_O3'].isel(lev=0, region=0, drop=True)
futurepol = futurepol_ratio_noland_region['SpeciesConc_O3'].isel(lev=0, region=0, drop=True)

prev_dO3_dNOx = present.shift(time=1)
transition = ((prev_dO3_dNOx < 1) & (present > 1))
transition_max = transition.sum(dim='time').max(dim=['nf', 'Ydim', 'Xdim'])
print(transition_max.values)

transition_min= transition.sum(dim='time').min(dim=['nf', 'Ydim', 'Xdim'])
print(transition_min.values)

transition_mean= transition.sum(dim='time').mean(dim=['nf', 'Ydim', 'Xdim'])
print(transition_mean.values)

[958 962 979 953 952]
[0 0 0 0 0]
[7.05244502 7.08246528 7.03139468 7.12485532 7.0598235 ]
